### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by S222em** [Garlic-Team/GCommands#137]
Hello, I found that when a message command gets used in a DM, nothing happens. But when a slash command is used in a DM, this error occurs: 

```
TypeError: Cannot read property 'id' of null
    at GCommandsClient.<anonymous> (/var/Discord/Bot/node_modules/gcommands/src/managers/GEventHandling.js:237:101)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

```javascript
let guildLanguage = await this.client.dispatcher.getGuildLanguage(interaction.guild.id);
let cooldown = await this.client.dispatcher.getCooldown(interaction.guild.id, interaction.author.id, commandos);
```
The check if the guild exists is missing. There should just be something like `if (!interaction.guild) return;`

I don't mind that it's impossible to use DM commands, but that error is rather annoying.

**Comment by xHyroM** [comment]
> 
> 
> Hello, I found that when a message command gets used in a DM, nothing happens. But when a slash command is used in a DM, this error occurs:
> 
> ```
> TypeError: Cannot read property 'id' of null
>     at GCommandsClient.<anonymous> (/var/Discord/Bot/node_modules/gcommands/src/managers/GEventHandling.js:237:101)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> ```
> 
> ```js
> let guildLanguage = await this.client.dispatcher.getGuildLanguage(interaction.guild.id);
> let cooldown = await this.client.dispatcher.getCooldown(interaction.guild.id, interaction.author.id, commandos);
> ```
> 
> There check if the guild exists is missing. There should just be something like `if (!interaction.guild) return;`
> 
> I don't mind that it's impossible to use DM commands, but that error is rather annoying.

Error is thrown when you run the command in DM? If not, are you sure you have intents turned on? https://gcommands.js.org/guide/guide/faq/#q-i-keep-getting-the-error-guild-is-not-defined

**Comment by S222em** [comment]
It works fine in a guild. It's just whenever I use a command in a DM channel. I have the GUILDS and GUILD_MEMBERS intents for now.

**Comment by xHyroM** [comment]
> 
> 
> It works fine in a guild. It's just whenever I use a command in a DM channel. I have the GUILDS and GUILD_MEMBERS intents for now.

Okay, so the problem is with the DMs. Thank you for writing to us. For now, we'll solve it by adding check

**Comment by xHyroM** [comment]
Next time, we'd appreciate it if you'd write to us at 
https://discord.gg/garlic

(https://github.com/Garlic-Team/GCommands/pull/128/commits/84655fbfc04d061dc24ffe51bc622868155036c6)
