### ISSUE TITLE
allowedMentions is not work

### ISSUE THREAD

**Issue by Kill00** [Garlic-Team/GCommands#158]
GCommands version : `^7.0.0-dev.1630320763`

Code : 
```js
const { Command } = require("gcommands");

module.exports = class ping extends Command {
    constructor(...args) {
        super(...args, {
            name: "ping",
            description: "DevTest",
        })
    }

    async run({ client, respond }) {
        respond({ content: `${client.ws.ping}ms!`, allowedMentions: {repliedUser: true} })
    }
}
```

I used `allowed Mentions: {repliedUser: true}` to mention but it doesn't work like below
![screenshot](https://cdn.discordapp.com/attachments/746594059501699085/882458889294057552/1.PNG)

Below is the message when it works normally.
![image](https://user-images.githubusercontent.com/70481054/131605526-cd12df94-6484-45af-a695-2cb9364d8667.png)

**Comment by S222em** [comment]
Try 
```js
allowedMentions: { parse: ['users'] }
```

**Comment by Kill00** [comment]
Still doesn't work, but thanks for the help :)

**Comment by Kill00** [comment]
#159
