### ISSUE TITLE
it says it doesnt have permission

### ISSUE THREAD

**Issue by astro-300** [Garlic-Team/GCommands#18]
![image](https://user-images.githubusercontent.com/80830712/120085565-484cdb80-c0a7-11eb-85e3-42f0e4bc64e4.png)

**Comment by xHyroM** [comment]
429 = need wait 20 seconds. Discord has rate limit

**Comment by xHyroM** [comment]
If it gives missing access it means the bot is not on the server/you didn't give it oauth2 rights to applications.commands
