### ISSUE TITLE
Buttons for message commands BOOLEAN argument.

### ISSUE THREAD

**Issue by anondev-sudo** [Garlic-Team/GCommands#183]
Please add buttons with text True and False to the message when you use message command when bot is prompting for BOOLEAN input

Also then there are optional arguments, add button with text Skip to the prompt message to skip it easier without typing skip to the channel.

**Comment by anondev-sudo** [comment]
Also there should be that when you write cancel to the channel, prompt will be cancelled and add button for it too

**Comment by S222em** [comment]
That's a good idea. Buttons will make it look fancy

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/169af6a4626b1f83b946a521852b1a45a2ed0eb0
