### ISSUE TITLE
GCommands Next

### ISSUE THREAD

**Issue by xHyroM** [Garlic-Team/GCommands#268]
Our Team is working on a full rewrite of GCommands to TS, with new features. It will be available publicly in a few days, in the `next` branch

![obrázok](https://user-images.githubusercontent.com/56601352/145376788-53170730-e5db-41e1-b973-cb163bcee2e5.png)

![obrázok](https://user-images.githubusercontent.com/56601352/145770656-4ae1360f-7f27-4a34-a3ab-8ec0269416d2.png)

Documentation: https://garlic-team.js.org/docs/#/docs/gcommands/next/general/welcome

**Comment by xHyroM** [comment]
# First Next Generation Version
https://www.npmjs.com/package/gcommands/v/0.1.0-nextdev.1639260391

**Examples**: https://github.com/Garlic-Team/GCommands/tree/next/example

**Comment by xHyroM** [comment]
We will also have a completely new and more automated system for pull requests, automatically updating dependencies unless it is a major release.

**Comment by xHyroM** [comment]
New documentation: https://garlic-team.js.org/#/docs/gcommands/next/general/welcome

**Comment by xhyrom** [comment]
We are working on gcommands-templates repo, gcommands-cli and official gcommands plugins

**Comment by xhyrom** [comment]
2 days until 1 month

**Comment by xhyrom** [comment]
Stable version released
