### ISSUE TITLE
Invalid form body on valid command names

### ISSUE THREAD

**Issue by OwendB1** [Garlic-Team/GCommands#295]
### Issue description

Current steps to reproduce unknown. Given error is:
[ERROR] 50035 Invalid Form Body
5.options[0].name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid
7.options[0].name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid
10.options[0].name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid

Trace: [TRACE] DiscordAPIError[50035]: Invalid Form Body
5.options[0].name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid
7.options[0].name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid
10.options[0].name[APPLICATION_COMMAND_INVALID_NAME]: Command name is invalid

### Code sample
Corresponding code samples for 5, 7 and 10 can be found below.

```typescript
new Command ({
	name: `eval`,
	description: `Evaluate given string as javascript. Locked down so only Owen can use it`,
	type: [CommandType.SLASH],
	inhibitors: [new ChannelOnly({ ids: [botconfig.commandsChannel] })],
	arguments: [
		{
			name: `code`,
			description: `code that should be evaluated`,
			type: ArgumentType.STRING,
			required: true, 
		},
	],

	run: ({ author, message, arguments: args }) => {
		if (author.id !== `190833902020067329`) return;
		try {
			const code = args.getString(`code`);
			let evaled = eval(code);
			
			if (typeof evaled !== `string`) evaled = require(`util`).inspect(evaled);

			const cleaned = clean(evaled);
			const finalMessages = Util.splitMessage(cleaned, {maxLength: 2000});
			finalMessages.forEach(msg => {
				message.channel.send({ content: `\`\`\`${msg}\`\`\``, code: `json` });
			});			
		} catch (err) {
			message.channel.send(`\`ERROR\` \`\`\`xl\n${clean(err)}\n\`\`\``);
		}
	}
});

function clean(text) {
	if (typeof (text) === `string`)
		return text.replace(/`/g, `\`` + String.fromCharCode(8203)).replace(/@/g, `@` + String.fromCharCode(8203));
	else return text;
}

new Command ({
	name: `keen`,
	description: `send a keen gif`,
	type: [CommandType.SLASH],
	inhibitors: [new ChannelOnly({ ids: [botconfig.commandsChannel, botconfig.trialStaffChannelID, botconfig.commandsChannel] })],

	run: ({ reply }) => {
		const embed = new MessageEmbed()
			.setImage(`https://i.imgur.com/D0cXFiW.gif`);
		reply({ embeds: [embed] });
	}
});

new Command ({
	name: `cleanups`,
	description: `Manually send the weekly cleanup count ping`,
	type: [CommandType.SLASH],
	inhibitors: [
		new ChannelOnly({ ids: [botconfig.commandsChannel] }),
		new UserRoles({ ids: botconfig.adminRoles })
	],
	
	run: async({ reply }) => {
		console.log(``); // placeholder for sending cleanups
		reply(`Attempting to trigger cleanup ping`);
	}
});
```

### GCommands version

9.0.0next

### Node.js version

v16.13.1

### Operating system

Windows 11

### Priority this issue should have

Medium (should be fixed soon)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by S222em** [comment]
Just want to point out to you that `author` is `user` now. Have not found the issue yet. Just tested some stuff and it works fine for me. Can you make a list of all your command names? That would help a lot!

**Comment by xhyrom** [comment]
I'll help too, but I'm not I'm home now 😐

**Comment by OwendB1** [comment]
I'm going to quickly refactor author to user then

**Comment by OwendB1** [comment]
refactored, same error persists.

**Comment by OwendB1** [comment]
List of command names without subcommands in same numeric order of errors: `assign, sync, dupoints, epochday, eval, help, keen, rolecount, roles, cleanups, engineersmessage, updateseparators, voice`

**Comment by S222em** [comment]
@OwendB1 I get the same type of error as you specified when providing an invalid name for a subcommand or subcommand group. You should search for the issue there. Names may ONLY include letters (no special characters like "!" or "?"), and can not be larger than 32 characters. If you can not find the issue, please send all the names of your subcommands here. Validation for names will be improved in upcoming versions to help you find the cause of the problem faster.

**Comment by OwendB1** [comment]
Copy that, the weird thing is that none of those commands that are erroring have subcommands.

**Comment by S222em** [comment]
> Copy that, the weird thing is that none of those commands that are erroring have subcommands.

You should look in all commands that have subcommands. I don't think you are even able to tell which command it's coming from with the trace.

**Comment by OwendB1** [comment]
I confirmed for myself it was perfectly sequential from top to bottom because I had a bunch more errors that I fixed. I'm going to switch the specific commands from slash to message to see if that fixes the trace

**Comment by OwendB1** [comment]
Found the issue, was wrongly counting, index starts 0 which makes sense. Arguments had capital letters in them.
