### ISSUE TITLE
Deprecate prefix commands

### ISSUE THREAD

**Issue by S222em** [Garlic-Team/GCommands#456]
### Feature

All context structures should be removed and replaced by a plain discord.js interaction class. This also means that message commands are not supported anymore.

- Discord itself wants all bots to switch to application commands before the set deadline for the privileged message content intent. This also means that verified bots **can't** use prefix commands anymore, because Discord will not accept requests for that usage.
- Certain things like modals can only be used with application commands.
- Application commands are generally easier to work with.
- Creating new bots with message commands should be discouraged.

Removing contexts and prefix commands will not impact existing small bots, as they can keep running v9. Contexts have also been designed to be like discord.js interaction class so users probably don't have to change anything.

This will also make the internal code of GCommands much less messy.

**Small summary:**
- Discord wants all bots to migrate to slash commands.
- Existing bots with message commands can keep running v9.
- Contexts are similar to discord.js interactions so much migration is not needed.

### Ideal solution or implementation

- [ ] All context structures should be removed and replaced by an interaction class provided by discord.js
- [ ] Remove support for prefix commands
- [ ] Types can be enhanced to narrow the different interaction types for commands and components

### Alternative solutions or implementations

A plugin can also be made for prefix command support.

**Comment by xhyrom** [comment]
I don't know if I would do that because some people (myself included) only use message commands as developer commands. Yes, you can indeed have a slash command and guildonly but still sometimes it is better to have a message command. I'd probably hold it here for a while to discuss it
