### ISSUE TITLE
Context ChannelId not getting populated

### ISSUE THREAD

**Issue by OwendB1** [Garlic-Team/GCommands#590]
### Issue description

Trigger any command in the bot's direct messages. Once you do it returns a stacktrace that points to the context constructor in which this.channelId = options.**channel**.id; is null. This is circumventable by changing the property to nullable `this.channelId = options.channel?.id;` but this might not fix the issue.

### Code sample

```typescript
TypeError: Cannot read properties of null (reading 'id')
 at new Context (C:\Users\owen\Documents\GitHub\thp-services\node_modules\gcommands\dist\lib\structures\contexts\Context.js:8:42)
    at new CommandContext (C:\Users\owen\Documents\GitHub\thp-services\node_modules\gcommands\dist\lib\structures\contexts\CommandContext.js:7:9)
```

### GCommands version

v10.0.0

### Node.js version

v16.13.1

### Operating system

Windows 11 or Ubuntu 22

### Priority this issue should have

High (immediate attention needed)

### Which gateway intents are you subscribing to?

GUILDS, GUILD_MEMBERS, GUILD_MESSAGES, DIRECT_MESSAGES

**Comment by xhyrom** [comment]
thanks, ill look into it 👍

**Comment by OwendB1** [comment]
Fixed this in my production environment by temporarily editing the line and pushing the file along in my repository workflows

**Comment by OwendB1** [comment]
Still waiting for official remedy but lower priority right now.

**Comment by xHyroM** [comment]
options.channelId should fix this

**Comment by xhyrom** [comment]
i will push fix soon
